# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ssh deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "mian" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js Build
      uses: actions/setup-node@v3
      with:
        node-version: 24.15.0
        cache: 'npm'
    - run: npm install --legacy-peer-deps
    - run: npm run docs:build
    - run: ls -l
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.YHY_SSH_HOST }}
        port: ${{ secrets.YHY_SSH_PORT }}
        username: ${{ secrets.YHY_SSH_USER }}
        password: ${{ secrets.YHY_SSH_PWD }}
        script: |
          whoami
          rsync -avz --delete ./.vitepress/dist /opt/1panel/www/sites/notes.tintinly.top/index/
